### ISSUE TITLE
[Feature] Safestart: RESTARTED

### ISSUE THREAD

**Issue by Bubbus** [CombinedArmsGaming/CAFE3#59]
Safestart doesn't work and hasn't for a long time now.  The fact remains that it's supposed to be a feature we have though.  It was initially disabled by me a couple years ago because it was broken and I didn't know how to fix it, but that's probably not the case anymore.

- [x] Fix safestart and return it to its old feature set.
- [x] See if there's a better way to message to players how much time is left in safestart.  
- [ ] If players are not made invulnerable during safestart, make sure they get this.  In case they decide to jump out of buildings or climb under tanks or w/e.
- [ ] From memory, safestart wouldn't affect AI which sometimes lead to awkward situations - rare but not never.  See how easy it is to disable AI whenever safestart is on.  

Side thoughts:
* If there's a good way to display a counting-down timer on the screen then we should do that for the 2nd criterion, because we can reuse that functionality later on to improve the "unconscious respawn wave" user experience.
* It may be a good idea to bake-in a mandatory period of AI deactivation whenever the object-scaling feature is enabled.  Placing AI on top of scaled objects usually results in dead AI because they fall through the object before the scaling takes effect.  If AI disabling is done as a part of this ticket, try to make it reusable for this purpose.

Separate tickets should be made for these side thoughts but I'm lazy - whoever takes on this ticket, remind me to make these side tickets before this one is closed.

**Comment by Cre8or** [comment]
Porting the original issue to the new format.

--

**Describe the bug**
Safestart doesn't work and hasn't for a long time now.

**To Reproduce**
Steps to reproduce the behavior:
1. Clone the framework
2. Export it to a mission
3. Start the mission
4. Notice that safestart is not in effect

**Expected behavior**
Safestart should (by default) be running on mission start as a safeguard against player misfires and other incidents, for the duration of client and server initialisation.

**Screenshots**
N/A

**Environmental Info:**
 - V+ Repo, although the issue is not limited to a specific repository
 - No CDLCs in use
 - Framework Version v1.3.0

**Additional context**
A rewrite of the safestart system is preferred in order to fold the `safestart` and `safeend` into a new component, simply called `ceasefire`. This would enable us to include additional functionalities, such as an on-screen display of the remaining ceasefire duration, aswell as a justification ("END EX", "technical issues", etc.).
